import 'package:flutter/material.dart';

const kTempTextStyle = TextStyle(
  fontFamily: 'Spartan MB',
  fontSize: 60.0,
);

const kMessageTextStyle = TextStyle(
  fontFamily: 'Spartan MB',
  fontSize: 50.0,
);

const kButtonTextStyle = TextStyle(
  fontSize: 30.0,
  fontFamily: 'Spartan MB',
);

const kConditionTextStyle = TextStyle(
  fontSize: 60.0,
);

const city = [
  'Banda Aceh',
  'Langsa',
  'Lhokseumawe',
  'Meulaboh',
  'Sabang',
  'Subulussalam',
  'Denpasar',
  'Pangkalpinang',
  'Cilegon',
  'Serang',
  'Tangerang Selatan',
  'Tangerang',
  'Bengkulu',
  'Gorontalo',
  'Banten',
  'Bangka Belitung',
  'Bali',
  'Aceh',
  'Jakarta',
  'Jambi',
  'Sungai Penuh',
  'Bandung',
  'Bekasi',
  'Bogor',
  'Cimahi',
  'Cirebon',
  'Depok',
  'Sukabumi',
  'Tasikmalaya',
  'Banjar',
  'Magelang',
  'Pekalongan',
  'Purwokerto',
  'Salatiga',
  'Semarang',
  'Surakarta',
  'Tegal',
  'Batu',
  'Blitar',
  'Kediri',
  'Madiun',
  'Malang',
  'Mojokerto',
  'Pasuruan',
  'Probolinggo',
  'Surabaya',
  'Pontianak',
  'Singkawang',
  'Banjarbaru',
  'Banjarmasin',
  'Palangkaraya',
  'Balikpapan',
  'Bontang',
  'Samarinda',
  'Tarakan',
  'Batam',
  'Tanjungpinang',
  'Bandar Lampung',
  'Metro',
  'Lampung',
  'Ternate',
  'Tidore Kepulauan',
  'Ambon',
  'Tual',
  'Bima',
  'Mataram',
  'Kupang',
  'Sorong',
  'Jayapura',
  'Papua',
  'Dumai',
  'Pekanbaru',
  'Makassar',
  'Palopo',
  'Riau',
  'Parepare',
  'Palu',
  'Bau-Bau',
  'Kendari',
  'Bitung',
  'Kotamobagu',
  'Manado',
  'Tomohon',
  'Bukittinggi',
  'Padang',
  'Padangpanjang',
  'Pariaman',
  'Payakumbuh',
  'Sawahlunto',
  'Solok',
  'Lubuklinggau',
  'Pagaralam',
  'Palembang',
  'Prabumulih',
  'Binjai',
  'Medan',
  'Padang Sidempuan',
  'Pematangsiantar',
  'Sibolga',
  'Tanjungbalai',
  'Tebingtinggi',
  'Yogyakarta',
];

const jabodetabek = [
  'Jakarta',
  'Bogor',
  'Depok',
  'Tangerang',
  'Bekasi',
];
